# example workflow for Polaris scans using the Black Duck Security Scan Action
# https://github.com/marketplace/actions/black-duck-security-scan
name: Polaris
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  polaris:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 23
        distribution: temurin
        cache: maven
    - name: Polaris Scan
      uses: blackduck-inc/black-duck-security-scan@v2.1.1
      with:
        polaris_server_url: ${{ vars.POLARIS_SERVER_URL }}
        polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
        polaris_assessment_types: 'SAST'
        polaris_application_name: MST-WebGoat
        polaris_project_name: MST-WebGoat
        polaris_reports_sarif_create: 'true'
        polaris_upload_sarif_report: 'true'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        mark_build_status: 'failure'
        polaris_waitForScan: 'true'


    - name: cmdLine
      id: cmdLine
      run: |
      EXIT_CODE=${{ steps.black-duck-security-scan.outputs.status }}
      echo "Black Duck Security Scan exit status - $EXIT_CODE"

        # include_diagnostics: true
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
#        include-hidden-files: true